//Let's try to understand the problem if we don't use a try-catch block.
package javafundamentls;

public class Exception_Try_CatuchBlock {

	public static void main(String[] args) {
		
		int data=100/0;// excption throws here
		
		System.out.println("rest of the code");

	}

}



